# Generated by Django 4.2.6 on 2023-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="date_and_time",
            field=models.DateTimeField(null=True),
        ),
    ]
